### PR TITLE
H2tank update

### PR DESCRIPTION
**Pull request by nareshsusarla**
## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by nareshsusarla** [comment]
@radhakrishnatg

**Comment by andrewlee94** [comment]
@nareshsusarla What is the status of this PR? We need to get it merged by the end of the month to meet the deliverable. At the moment it looks like you have some test failures you need to work through.

**Review by dguittet — CHANGES_REQUESTED** [review]
The python files look good to me. However, the docs aren't showing the math formatting: https://dispatches--61.org.readthedocs.build/en/61/models/nuclear/hydrogen_tank.html

**Review by dguittet — CHANGES_REQUESTED** [review]
There are still some issues with the docs:
1. The sigma for sum isn't showing up
2. There's a \U in red
3. dt missing from the Fout * Hout term
4. U or E for internal energy? Both are being used but the key only describes U

**Review by klfrick2 — APPROVED** [review]
Looks good to me. All the docs build. Tests pass.

**Review by dguittet — DISMISSED** [review]

**Review by klfrick2 — APPROVED** [review]

**Review by dguittet — APPROVED** [review]

**Pull request merged**
