### PR TITLE
Adding supercritical powerplant flowsheet with thermal oil storage

### PR DESCRIPTION
**Pull request by Andresj89**
## Summary
- This a WIP PR that adds a supercritical power plant flowsheet coupled with thermal energy storage using thermal oil.
- The flowsheet includes 4 disjuncts, 2 for steam extraction and 2 for steam sinks.
- The flowsheet considers the minimization of the storage HX area as a temporary objective function.
- An exhaustive enumeration is currently reporting the correct solution, however the GDP optimization still requires additional work.

### CODE REVIEW

**Comment by ksbeattie** [comment]
@Andresj89, is this ready for review yet?  Will you be adding docs and tests for this as well?

**Comment by jghouse88** [comment]
@Andresj89 Can you please mark this as not draft so that we can review and merge it in?

**Comment by Andresj89** [comment]
@jghouse88 I just made this PR ready for review

**Comment by esrawli** [comment]
@Andresj89 The model runs and gives an optimal solution when GDPopt is used. I see is missing scaling factors that I would recommend including

**Comment by Andresj89** [comment]
@esrawli thanks for the suggestion. I just pushed the corrections.

**Review by nareshsusarla — APPROVED** [review]
Looks good. One suggestion, it may be a good idea to have a function to fix the disjuncts and run only specific NLPs. As this model grows to include more disjuncts, the run NLP function may come handy

**Review by jghouse88 — APPROVED** [review]
LGTM

**Pull request merged**
