### PR TITLE
Update prerelease requirement for IDAES 2022 Aug release

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Changes proposed in this PR:

- Update prerelease requirement for IDAES to IDAES/idaes-pse#908's head branch (on @radhakrishnatg's fork)

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by radhakrishnatg** [comment]
@lbianchi-lbl The test failures are because of line 116 in this file https://github.com/gmlc-dispatches/dispatches/blob/main/dispatches/models/nuclear_case/flowsheets/nuclear_flowsheet_multiperiod_class.py#L116
Deleting this line should resolve the test failures. I ran the notebook locally, and it ran without any errors.
Can I make the change and push it to your branch?

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl The test failures are because of line 116 in this file https://github.com/gmlc-dispatches/dispatches/blob/main/dispatches/models/nuclear_case/flowsheets/nuclear_flowsheet_multiperiod_class.py#L116
> Deleting this line should resolve the test failures. I ran the notebook locally, and it ran without any errors.
> Can I make the change and push it to your branch?

@radhakrishnatg thanks for looking into this. Yes,please feel free to push the changes to my branch for this PR.

**Comment by radhakrishnatg** [comment]
@lbianchi-lbl I tried to push the changes to your branch, and it said "permission denied". I'm sorry, I may not have done it correctly. This is what I did:
```
git remote add ludovico-fork <git-link>
git fetch ludovico-fork
git checkout ludovico-fork/update-idaes-908
<made the change and committed it>
git push ludovico-fork ludovico-fork/update-idaes-908
```

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl I tried to push the changes to your branch, and it said "permission denied". I'm sorry, I may not have done it correctly. This is what I did:
> ```
> git remote add ludovico-fork <git-link>
> git fetch ludovico-fork
> git checkout ludovico-fork/update-idaes-908
> <made the change and committed it>
> git push ludovico-fork ludovico-fork/update-idaes-908
> ```
> 

I see, thanks for trying and sorry about the permissions issue. I'll try to make the change myself and then you can review it and suggest changes through the PR review system.

**Comment by radhakrishnatg** [comment]
@lbianchi-lbl The tests are passing now, so can this be merged now or do we need to wait until IDAES 908 is merged?

**Comment by lbianchi-lbl** [comment]
@radhakrishnatg I think we should proceed as follows:

- First, we get IDAES/idaes-pse#908 merged into `main`
- Once that's in, I'll update gmlc-dispatches/idaes-pse and create a new tag
- I'll update this PR so that the prerelease `idaes-pse` requirement points to the new tag
- At that point, we can merge this PR

**Comment by lbianchi-lbl** [comment]
Update: I've implemented the changes suggested by @esrawli. API-wise, these seem to work for the most part; however, there are still failures and/or possible performance issues, both affecting `test_discharge_usc_powerplant.py`:

- The `test_main_function` test takes almost 1 h to complete. I don't have exact timings for the pre-6.4.2 version, but I seem to remember that the runtime was roughly comparable with its counterpart in `test_charge_usc_powerplant.py` (which now takes ~5 min)
- AttributeError when trying to access `m.fs.charge`. Looking at the traceback, it seems that the function that's being called is `charge_design_ultra_supercritical_power_plant.print_model()`, whereas the function that's being registered as a callback is `discharge_design_ultra_supercritical_power_plant.print_model()`, which has the same name but is a different function. Is it possible that setting an option through `s = SolverFactory("gdpopt.ric"); s.CONFIG.call_after_subproblem_solve = ...` could somehow leak and/or shadow when doing the same for a separate instance in a different module? `s = SolverFactory("gdpopt.loa")`?

```log
model = <pyomo.core.base.PyomoModel.ConcreteModel object at 0x7f356425b470>

    @pytest.mark.integration
    def test_usc_discharge_model(model):
        # Add missing functions to complete the discharge model (add bounds
        # and disjunctions)
        discharge_usc.add_bounds(model, power_max=power_max)
        discharge_usc.disconnect_arcs(model)
        discharge_usc.add_disjunction(model)
    
        # Add design optimization problem
        discharge_usc.model_analysis(model, heat_duty=heat_duty)
    
        opt = SolverFactory('gdpopt.ric')
        opt.CONFIG.tee = False
        opt.CONFIG.mip_solver = 'cbc'
        opt.CONFIG.nlp_solver = 'ipopt'
        opt.CONFIG.init_algorithm = "no_init"
        opt.CONFIG.subproblem_presolve = False
        _prop_bnds_root_to_leaf_map[
            ExternalFunctionExpression] = lambda x, y, z: None
    
>       result = opt.solve(model, mip_solver="cbc")

dispatches/case_studies/fossil_case/ultra_supercritical_plant/storage/tests/test_discharge_usc_powerplant.py:127: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pyomo/contrib/gdpopt/algorithm_base_class.py:119: in solve
    self._solve_gdp(model, config)
/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pyomo/contrib/gdpopt/ric.py:84: in _solve_gdp
    discrete_problem_util_block, subproblem_util_block, config)
/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pyomo/contrib/gdpopt/oa_algorithm_utils.py:26: in _fix_discrete_soln_solve_subproblem_and_add_cuts
    config)
/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pyomo/contrib/gdpopt/solve_subproblem.py:350: in solve_subproblem
    config)
/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pyomo/contrib/gdpopt/solve_subproblem.py:330: in call_appropriate_subproblem_solver
    config.call_after_subproblem_solve(solver, subprob, subprob_util_block)
dispatches/case_studies/fossil_case/ultra_supercritical_plant/storage/charge_design_ultra_supercritical_power_plant.py:2518: in print_model
    nlp = nlp_model.fs.charge
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <idaes.core.base.process_block._ScalarFlowsheetBlock object at 0x7f35673a3e90>
val = 'charge'

    def __getattr__(self, val):
        if val in ModelComponentFactory:
            return _component_decorator(
                self, ModelComponentFactory.get_class(val))
        # Since the base classes don't support getattr, we can just
        # throw the "normal" AttributeError
        raise AttributeError("'%s' object has no attribute '%s'"
>                            % (self.__class__.__name__, val))
E       AttributeError: '_ScalarFlowsheetBlock' object has no attribute 'charge'

/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/pyomo/core/base/block.py:620: AttributeError
```

**Comment by lbianchi-lbl** [comment]
Closing this as the fixes needed for Pyomo 6.4.2 compatibility have already been implemented in #141.

**Pull request closed without merging**
