### PR TITLE
Update NE double loop notebook for RT-bidding and Backcaster

### PR DESCRIPTION
**Pull request by dguittet**
## Addresses issue:

#132 

To be merged after https://github.com/IDAES/idaes-pse/pull/824 and https://github.com/IDAES/idaes-pse/pull/855 and 
## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by radhakrishnatg** [comment]
@dguittet I cannot find the `Backcaster` class in `idaes.apps.grid_integration.forecaster`. Is it defined on your local machine?

**Comment by dguittet** [comment]
@radhakrishnatg Ah it hasn't been merged into IDAES yet: https://github.com/IDAES/idaes-pse/pull/870

Looks like we need some reviews on that PR

**Comment by radhakrishnatg** [comment]
Thank you, @dguittet ! Until the IDAES PR is merged, can I keep using the `PlaceHolderForecaster`? If I replace `Backcaster` with `PlaceHolderForecaster` in the double loop notebook, will it work?

**Comment by dguittet** [comment]
Sorry I'm not sure how I closed this, might have been an accidental click.

I'm not sure if `PlaceHolderForecaster` will work or not as I haven't tried. I think as long as that class has the required functions implemented, it would not matter how the forecast was generated and it would be ok to switch it out.

**Comment by radhakrishnatg** [comment]
@dguittet @nareshsusarla @esrawli @adowling2 @jghouse88 @lbianchi-lbl @ksbeattie A quick update on IDAES PR 870. In short, we need 870 at least for the renewables case study. For the remaining two case studies, see the description below:

The `PlaceHolderForecaster` class has been modified in the IDAES PR 855, and the updated class is not compatible with the old version. In addition, the `csv` file containing the data required for the `PlaceHolderForecaster` class has been removed from the IDAES repo. So, the current Jupyter notebooks containing the double loop simulation stuff for both nuclear and fossil case studies will fail. 

We could update the notebooks with the new `PlaceHolderForecaster` class and also add the data it needs to the notebook. But, https://github.com/IDAES/idaes-pse/pull/870 adds two more methods to the `PlaceHolderForecaster` class. @adowling2 and @Xinhe-Chen Do you know if `fetch_hourly_stats_from_prescient` and `fetch_day_ahead_stats_from_prescient` are needed for the changes in IDAES PRs 824 and 855? If yes, we need to merge IDAES PR 870 as soon as possible. 

After 870 is merged, does it make sense to keep using the `PlaceHolderForecaster` class in the Jupyter notebooks instead of `Backcaster`?

**Comment by adowling2** [comment]
@radhakrishnatg I cannot quickly answer your question about IDAES PR 824 and 855.

Yes, let's get 870 ready to merge. From my review, the only thing is to add a few more tests. We can then discuss if it is best to close the PR and copy it into a new PR that does not include any of the IDAES 2.0 changes (beyond the last release candidate). @ksbeattie @lbianchi-lbl what do you think about this? We could have dispatches branch on IDAES that we merge into for now. We can then make changes via small PRs to get the grid stuff working. Then those can get merged into IDAES main for the big November IDAES 2.0 release.

**Comment by radhakrishnatg** [comment]
Sounds good @adowling2 ! I briefly reviewed PR 870 this morning. I will take a look at it on more time this afternoon and add my review. I'm meeting @Xinhe-Chen tomorrow to discuss about the tests.

**Comment by lbianchi-lbl** [comment]
@adowling2 @radhakrishnatg These seems reasonable ideas to consider, but before being able to do that, I just wanted to bring to your attention a new, unrelated issue that's currently affecting all code that depends on Egret/Prescient, which is being tracked in #145. More specifically, this will prevent the code in IDAES/idaes#870 being run in CI until resolved.

**Comment by radhakrishnatg** [comment]
Closing the PR, since the changes in this PR have been made in #151.

**Pull request closed without merging**
