### PR TITLE
Repo reorganization

### PR DESCRIPTION
**Pull request by radhakrishnatg**
## Addresses issue:
#104 
#135 

## Summary/Motivation:
Reorganizes the DISPATCHES repository

## Changes proposed in this PR:
- The new folder `unit_models` now contains all the unit models in one place
- The new folder `properties` now contains all the property packages in one place
- Updated the imports where needed
- Removed the old thermal oil property package

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
@radhakrishnatg I think the ReadTheDocs build failures are due to the `.. module::` directives not having been updated to use the new import paths.

You should be able (at least as a starting point) to search for `.. module::` in all `.rst` files and update each import paths to the correct one.

**Comment by radhakrishnatg** [comment]
Thank you @lbianchi-lbl ! That worked! However, there is another test that is failing now. It says that it cannot find `dispatches/case_studies/renewables_case/data/Wind_Power_Dispatch.csv` file. But that file is in the repository, so I don't know why it is complaining.

**Comment by lbianchi-lbl** [comment]
> Thank you @lbianchi-lbl ! That worked! However, there is another test that is failing now. It says that it cannot find `dispatches/case_studies/renewables_case/data/Wind_Power_Dispatch.csv` file. But that file is in the repository, so I don't know why it is complaining.  

@radhakrishnatg I think this is because the packages specified for `package_data` in `setup.py` are still using the old import paths. Once these are updated to the new paths, the tests should pass.

**Comment by radhakrishnatg** [comment]
Thank you so much, @lbianchi-lbl ! I have updated the imports, and the tests are passing now.

@dguittet @nareshsusarla @jghouse88 @adowling2 I have reorganized the repository as per the discussion we had sometime back (see #104 ) Please let me know if you have any suggestions or changes to this. If you are okay with this structure, I would like to get this PR merged as soon as possible so that everyone can update their forks before they create new PRs.

**Review by jghouse88 — APPROVED** [review]
LGTM. I took a look at the repo structure and makes sense.

**Comment by dguittet** [comment]
LGTM

**Review by dguittet — APPROVED** [review]

**Pull request merged**
