### PR TITLE
Raven and Teal integration

### PR DESCRIPTION
**Pull request by radhakrishnatg**
## Addresses issue:
#86 and #90

## Summary/Motivation:
This PR replaces #150

## Changes proposed in this PR:
- Adds a Jupyter notebook that demonstrates usage of TEAL for constructing cashflow expressions
- Also add utilities to construct synthetic realizations 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by joshua-cogliati-inl — APPROVED** [review]
Looks fine to me.

**Review by dguittet — DISMISSED** [review]
Thanks @radhakrishnatg I was able to use the install instructions and ARMA_Model files to generate synthetic LMPs

**Comment by lbianchi-lbl** [comment]
@radhakrishnatg I tried running the notebook through the test framework locally in a Windows VM in an environment where RAVEN and TEAL are installed. It seems to run just fine, but then ultimately fails because of one of the cells exceeding the default timeout (2000 s -> ~30 min). Is this in line with the runtime you get when running locally? Is there any way this example could be tweaked so that the notebook executes in 10 minutes or so?

image

**Comment by radhakrishnatg** [comment]
@lbianchi-lbl I could run all the cells in the notebook within 10 minutes on my local machine. I do not know why that cell is taking more than half an hour. Also, I'm running the simplest case possible in that cell. So, could you please try running the notebook once again and let me know if it still takes longer than half an hour?

**Comment by lbianchi-lbl** [comment]
@radhakrishnatg OK, I see. I've tried re-running and the results are the same. I guess my resource-starved VM might be to blame, in which case we could just check how long it takes on the GHA runners. In the off-chance that some package version might be affecting that, could you run `pip list` in your local environment and paste the output here?

**Comment by radhakrishnatg** [comment]
@lbianchi-lbl I do not have my work laptop with me. I will be out of office starting tomorrow and I will be back Thursday of next week. Is there any other thing I could try to know what is causing it take more time? Also, the cell which is causing the issue is also present in the `multiperiod_design_pricetaker.ipynb` notebook. It is strange why it can run in less than 30 min in the other notebook but not in this notebook.

**Comment by lbianchi-lbl** [comment]
@radhakrishnatg No worries, I can look into it. Worst case, we can skip that cell since the RAVEN/TEAL setup happens in the first cells (which seem to run just fine).

Also, good point about `multiperiod_design_pricetaker.ipynb` - I can try to run the same exact command using that notebook and see if the long runtime also occurs.

**Comment by lbianchi-lbl** [comment]
It looks like running the TEAL notebook in CI mostly works, but there seems to be a solver error causing cells 28 and 29 to fail.

Given that:

- The notebook had already been approved by reviewers before the reviews were "invalidated" after merging in unrelated changes
- We're not currently able to reproduce this behavior locally (where the notebook either works fine, as per @radhakrishnatg and the reviewers, or fails in a different way, as per my testing)

I'll go ahead and merge this after having:

- Added a skip marker for the affected cells (only affects the notebook while being executed by the test framework)
- Opened #191 to track future progress in investigating the error

**Comment by joshua-cogliati-inl** [comment]
Thank you @lbianchi-lbl

**Pull request merged**
