### PR TITLE
NE case study

### PR DESCRIPTION
**Pull request by radhakrishnatg**
## Addresses issue:

N/A

## Summary/Motivation:

This PR adds the flowsheet and pricetaker optimization models for the generic nuclear case study.

## Changes proposed in this PR:
- Adding a flowsheet model and initialization methods for the generic nuclear case study
- Adding functions for setting up a multiperiod optimization model
- Adding a Jupyter notebook demonstrating the formulation of a stochastic multiperiod optimization problem for the nuclear case study.
- Adding a simplified hydrogen tank model that only keeps track of material flows, and ignores enthalpy balance.
- Adding stochastic multiyear LMP signal generated by FORCE using the 2019/2020 NYISO price data.
- Fixed a pyomo deprecation warning in `elec_splitter.py`
- Modified the initialization method in `pem_electrolyzer.py` to calculate the correct value of the molar flowrate of the outlet stream.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by radhakrishnatg** [comment]
@dguittet I made minor modifications to the PEM electrolyzer model (`dispatches/models/renewables_case/elec_splitter.py`) and the electricity splitter model (`dispatches/models/renewables_case/elec_splitter.py`).

- Fixed a Pyomo deprecation warning in the electricity splitter model
- Modified the PEM's initialization method slightly. Earlier, the initialization method was not computing the flowrate of hydrogen. I added two lines to do that. 

Please let me know if you are okay with these changes. Thank you!

**Comment by dguittet** [comment]
@radhakrishnatg Thanks for looping me in! I have also modified in PEM electrolyzer's initializer: https://github.com/dguittet/dispatches/blob/93d8d34901a3add76d5cec16ce7409c768be1b18/dispatches/models/renewables_case/pem_electrolyzer.py#L122

We need to decide how to merge them.

**Comment by radhakrishnatg** [comment]
@dguittet Thank you for the link! I see that you are using `to_json` and `from_json` methods. Based on my understanding, these methods may make things a little bit slow (@jghouse88  correct me if this is not the case). What you had earlier was sufficient. We just need to update the flowrate value using the `efficiency_curve` equation. Pyomo has a simple function to do that (which is what I did). This way, we can avoid one more IPOPT solve in the initialize method. This is what I have:
```
def initialize(self, **kwargs):
        self.outlet_state.initialize(hold_state=False)

        for t in self.flowsheet().config.time:
            calculate_variable_from_constraint(self.outlet.flow_mol[t],
                                               self.efficiency_curve[t])
```

Since you fixed the issue and made a lot more changes to the PEM electrolyzer model, I will not include the file in this PR. This will avoid merge conflicts.

**Comment by dguittet** [comment]
@radhakrishnatg Thanks for the detailed response! Sounds like the initialization you're doing is sufficient and more performant, so I think we should go with that one instead! I can resolve the merge conflict later, now that I know which changes to keep.

**Review by klfrick2 — APPROVED** [review]
This looks good on my end! Nicely done!

**Comment by radhakrishnatg** [comment]
@dguittet Since Jaffer is on vacation, I was wondering if you have some time to review this PR. The goal is to merge this PR before April's internal release. If yes, I will fix the codecov errors soon and inform you. Thank you very much for your help!

**Comment by dguittet** [comment]
@radhakrishnatg Yes, happy to review. Sorry for the delay. It looks good so far, but I'll wait for you to add the tests for the multiperiod model.

**Comment by radhakrishnatg** [comment]
Thank you so much, @dguittet! I will add the tests soon and inform you.

**Review by dguittet — APPROVED** [review]
Tests are passing and I was able to run `dispatches/models/nuclear_case/flowsheets/multiperiod_design_pricetaker.ipynb` successfully. Looks great!

**Review by klfrick2 — APPROVED** [review]
Excellent work. This looks good to me.

**Comment by radhakrishnatg** [comment]
Thank you, @dguittet and @klfrick2

**Comment by radhakrishnatg** [comment]
@lbianchi-lbl This PR is now ready to be merged. It has a Jupyter notebook which we can use for #77 Please let me know if there is anything I can do related to that issue.

**Pull request merged**
