### PR TITLE
Dynamic Surrogates for Market Outcomes

### PR DESCRIPTION
**Pull request by Xinhe-Chen**
## Changes proposed in this PR:
- Add time series clustering - neural network dynamic surrogate model for the dispatch frequency. 
- 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by Xinhe-Chen** [comment]
@adowling2 I have updated the automation codes as we discussed. Here is the link 
https://github.com/Xinhe-Chen/dispatches/blob/dynamic_surrogates/dispatches/workflow/train_market_surrogates/dynamic/dy_surrogate_automation.py
Please review it and let me know your thoughts.

**Comment by Xinhe-Chen** [comment]
The PR will be ready to review later today. I will remove all the picture files and csv/h5 files in this PR.

**Comment by Xinhe-Chen** [comment]
@ksbeattie Hi Keith, I got an import package error in the testing. I suppose this error is due to the lack of dependency on those packages. 
image

**Comment by lbianchi-lbl** [comment]
> @ksbeattie Hi Keith, I got an import package error in the testing. I suppose this error is due to the lack of dependency on those packages. image

Yes, I believe you're right. My suggestion would be the following:

- For the moment (i.e. while this PR is being prepared for review), add the `tslearn` requirement to `setup.py`, e.g. just above the line containing `*SPECIAL_DEPENDENCIES`
- Repeat for any other dependency that's currently missing and is needed to run the code (including tests) in this PR
- When the PR is in the final phases of the review process, we can think if it makes sense to group those dependencies to make them optional, e.g. as an `extras_require` target or a separate `requirements-*.txt` file

**Comment by Xinhe-Chen** [comment]
Open new PR #163 to replace this PR.

**Pull request closed without merging**
