### PR TITLE
RE Optimization w/ Dynamic Surrogates

### PR DESCRIPTION
**Pull request by dguittet**
## Addresses issue:
Wind + PEM Hybrid Optimization for December Milestone

Requires IDAES branch for grid integration changes: https://github.com/IDAES/idaes-pse/pull/1019

Files for running conceptual design w/ dynamic surrogates:
- `dispatches.case_studies.renewables_case/RE_surrogate_optimization.py`
- `dispatches.case_studies.renewables_case/SurrogateDesignResults.ipynb`: shows cost curve, and optimal size surfaces of surrogate model vs prescient sweep; upcoming analysis on comparison with double loop revenue results

Files for running Double Loop with parameterized bid curve:
- `workflow.parametrized_bidder.py`: class interface for a bidder, implementation of a DataFrame-based PerfectForecaster
- `dispatches.case_studies.renewables_case.PEM_parametrized_bidder.py`: implementation of bidder using Wind + PEM bid structure from Prescient sweeps
- `dispatches.case_studies.renewables_case/wind_PEM_double_loop.py`: implementation of a grid-integration wrapper for the Wind + PEM flowsheet model
- `dispatches.case_studies.renewables_case/run_double_loop_PEM.py`: script to run the double loop

## Summary:

Wind size is fixed to the original plant size (847 MW for 303_WIND_1) since the parameter sweep didn't vary the wind plant size

Optimal design:

Wind capacity = 847.0 MW
PEM capacity = 247.70494311964453MW
Plant bid = $29.711626518965524
Plant Revenue Annual = $24927.081507569157
Plant NPV = $-1252263849.6855943

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
5. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by Xinhe-Chen** [comment]
Hi Darice, I guess you are creating a branch based on the dynamic_surrogates branch in my repo. I think I have made a lot of updates to that branch and deleted a lot of unnecessary files. I am trying to get that branch merged to the dispatches but I get the same errors in the tests as you are having here.

**Comment by adowling2** [comment]
@dguittet @Xinhe-Chen Tag people when this is ready to review.

**Comment by dguittet** [comment]
Hello @radhakrishnatg @nareshsusarla @esrawli, here is the branch containing the code to run the double loop using the optimized system & bid variables. 

You will need to implement your own version of 
`dispatches.case_studies.renewables_case.PEM_parametrized_bidder.py` and `dispatches.case_studies.renewables_case/run_double_loop_PEM.py` (see PR description for high level info and see comments in the code for more details).

If you haven't written it already, you'll also need a version of the `dispatches.case_studies.renewables_case/wind_PEM_double_loop.py`.

Regarding forecasts, I did not need price forecasts since the bid curve is not generated via a stochastic program as before, but is now a constant curve that was optimized during the dynamic surrogate design.

Let me know if anything is not clear!

**Comment by dguittet** [comment]
Closing to move over to https://github.com/gmlc-dispatches/dispatches/pull/172

**Pull request closed without merging**
