### PR TITLE
Add CI workflow to test RAVEN integration

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Changes proposed in this PR:
- Add RAVEN requirements in dedicated `requirements-raven.txt` file
- Add CI workflow to ensure RAVEN works on all environments supported by DISPATCHES

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by joshua-cogliati-inl** [comment]
I would recommend a different test (`doc/workshop/forwardSampling/exercises/1_sample_and_plot.xml ` plots to `screen`) such as `tests/framework/user_guide/ForwardSamplingStrategies\forwardSamplingGrid.xml`

**Comment by GabrielSoto-INL** [comment]
if additional (simple) TEAL tests are of interest, I would recommend `TEAL/tests/Cash_Flow_input_NPV.xml`. an additional one that might pertain more to #150 would be `TEAL/tests/PyomoTest.py` (both found [here](https://github.com/idaholab/TEAL/tree/devel/tests))

**Comment by joshua-cogliati-inl** [comment]
@lbianchi-lbl 
```  python -c "
  from raven.ravenframework.utils import xmlUtils; print(xmlUtils)
  from raven.scripts import externalROMLoader; print(externalROMLoader)
  "
```
This should probably be:
```
 python -c "
  from ravenframework.utils import xmlUtils; print(xmlUtils)
  from ravenframework import ROMExternal; print(ROMExternal)
  "
```
If there is code still using externalROMLoader let me know and I can suggest how to modify it to switch to ROMExternal.  
The pip package installs RAVEN into ravenframework, not raven (There was already a different raven in pip)

Thanks.

**Comment by lbianchi-lbl** [comment]
> If there is code still using externalROMLoader let me know and I can suggest how to modify it to switch to ROMExternal. The pip package installs RAVEN into ravenframework, not raven (There was already a different raven in pip)
> 

Thanks for looking into this @joshua-cogliati-inl. For the import checks, my approach was to look at #150 and collect any RAVEN/TEAL imports used there. In particular, the `externalROMLoader` is taken from:

https://github.com/gmlc-dispatches/dispatches/blob/9532ad2a8bdc9eb35546e4ef52cbe60ffd1fa705/dispatches/case_studies/nuclear_case/SynHist_integration.py#L33

**Comment by joshua-cogliati-inl** [comment]
> https://github.com/gmlc-dispatches/dispatches/blob/9532ad2a8bdc9eb35546e4ef52cbe60ffd1fa705/dispatches/case_studies/nuclear_case/SynHist_integration.py#L33

Thanks, I left some review comments over at that pull request.

**Comment by joshua-cogliati-inl** [comment]
We released raven-framework 2.2 , so can you switch requirements-raven.txt to use that instead of the release candidate? I think that should fix at least one of the failures.

**Comment by lbianchi-lbl** [comment]
> We released raven-framework 2.2 , so can you switch requirements-raven.txt to use that instead of the release candidate? I think that should fix at least one of the failures.

@joshua-cogliati-inl thanks, I was just about to post that https://github.com/idaholab/raven/commits/devel/ravenframework/ROMExternal.py seems to have been added recently and therefore was probably not included in the code version that was being used here. I'll update the requirements with the non-RC version.

**Review by joshua-cogliati-inl — APPROVED** [review]
This looks fine to me.

**Comment by lbianchi-lbl** [comment]
The notebook execution checks are failing because of #167, but I think we should merge this anyway since the failures are not related to the content of this PR.

**Pull request merged**
