### PR TITLE
Fix RE Notebook Check

### PR DESCRIPTION
**Pull request by dguittet**
## Addresses issue: 
#176

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by dguittet** [comment]
@ksbeattie @lbianchi-lbl There are failing tests still but the notebook completes in time

**Comment by lbianchi-lbl** [comment]
For reference, this seems to be the relevant updates to the source code cells:

image

**Review by lbianchi-lbl — DISMISSED** [review]

**Review by ksbeattie — DISMISSED** [review]
LGMT

**Comment by lbianchi-lbl** [comment]
Closing this in favor of #190 which is on a non-`main` branch.

**Pull request closed without merging**
