### PR TITLE
Remove scripts and updating README addheader use

### PR DESCRIPTION
**Pull request by ksbeattie**
## Addresses issue:

The `scripts/` dir is out of date and gives incorrect instructions on how to update the copyright header info at the top of each `.py` file.

## Changes proposed in this PR:
- Remove the `scripts/` dir
- Update the README with instructions on how to use `addheader` to update copyright header info

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
> @dangunter & @lbianchi-lbl while I was in here, I noticed that we should also update the year in the `header_text.txt` file (from 2021 to 2022), then update all the headers (which would change all the files).
> 
> I didn't do that here.  What do you think, should I?

Thanks for spotting that. I think updating the year here makes sense as it's related.

**Review by lbianchi-lbl — COMMENTED** [review]
:+1: Looks good.

**Review by lbianchi-lbl — APPROVED** [review]
:+1: Looks good!

**Review by dangunter — APPROVED** [review]
Looks good

**Review by lbianchi-lbl — APPROVED** [review]

**Pull request merged**
