### PR TITLE
Add core infra for RE double-loop simulation

### PR DESCRIPTION
**Pull request by xiangao1**
## Addresses issue:
Address the first task here: https://github.com/gmlc-dispatches/dispatches/pull/95#issuecomment-1167645040

## Summary/Motivation:
- Add the necessary functions and classes for renewable case study double loop simulation.

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by dguittet** [comment]
Shouldn't [test_multiperiod_wind_battery_doubleloop.py](https://github.com/gmlc-dispatches/dispatches/pull/95/files#diff-4d49beb0fbe95937f5757c86be5b456f6e68dac416dd5cd18a3a7fe6a6b453ce) also be added?

**Comment by lbianchi-lbl** [comment]
> Shouldn't [test_multiperiod_wind_battery_doubleloop.py](https://github.com/gmlc-dispatches/dispatches/pull/95/files#diff-4d49beb0fbe95937f5757c86be5b456f6e68dac416dd5cd18a3a7fe6a6b453ce) also be added?

@dguittet thanks for bringing this up. Without knowing the details of the code being tested, I can already see that `test_multiperiod_wind_battery_doubleloop.py` won't work out of the box (e.g. explicitly requesting `gurobi` as the solver). 

Therefore, I would suggest to merge this in (so that it can make it into the release candidate today) and add the test file in another PR later.

**Comment by xiangao1** [comment]
@lbianchi-lbl can we use cbc instead then?

**Comment by dguittet** [comment]
@lbianchi-lbl Adding it in a later PR works too.

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl can we use cbc instead then?

I think so, assuming that (an appropriate version of) `cbc` is available after running `idaes get-extensions` on both Windows and Ubuntu.

**Pull request merged**
