### PR TITLE
Make DISPATCHES compatible with IDAES 2.0

### PR DESCRIPTION
**Pull request by radhakrishnatg**
## Summary/Motivation:
This PR updates all the scripts and notebooks to be compatible with IDAES 2.0

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
@radhakrishnatg It looks like the error with the tags could be due to changes in the `svg_tag()` method in IDAES:

image

While I'm not familiar with the code, my guess would be to change the arguments of `svg_tag()` in `ultra_supercritical_powerplant.py:view_result()` so that it becomes:

```py
svg_tag(svg=f, tag_map=tags, outfile=outfile)
```

**Comment by radhakrishnatg** [comment]
Thank you @lbianchi-lbl ! Unfortunately, that was not sufficient. I had to save tags as `ModelTag` objects, and then put all the tags in a `ModelTagGroup` object. I made those changes and now that test is passing. Now, the only test that is failing is the discharge flowsheet in the fossil case study. As you suggested on Monday, we can skip that test for this PR. I opened an issue #153 to track it.

@dguittet Please take a look at the changes to the scripts and notebooks related to the renewable case study
@nareshsusarla @esrawli Please take a look at the changes to the fossil case study. The `HeatExchanger` model had quite a few changes, so you will notice a lot of changes related to that.

**Comment by lbianchi-lbl** [comment]
@radhakrishnatg thanks for checking that. The only thing left before merging seems to be making sure that the currently failing tests are skipped.

Could you apply the changes described here (i.e. adding the `pytest.mark.skip` decorator to the two failing functions): https://github.com/gmlc-dispatches/dispatches/pull/141#issuecomment-1244077898? If you want, you can update the `reason=` to point to issue #153.

**Review by dguittet — APPROVED** [review]
Looks great @radhakrishnatg

**Comment by radhakrishnatg** [comment]
Thank you @dguittet ! I had to re-run one of the Jupyter notebook to address the test failure. Could you please approve the PR once again?

**Review by dguittet — DISMISSED** [review]

**Comment by lbianchi-lbl** [comment]
@radhakrishnatg @dguittet I think the `DoubleLoopOptimization.ipynb` notebook failures could (also?) be due to the fact that the IDAES version that's being used for that notebook, i.e. https://github.com/dguittet/idaes-pse@2.0.0.a4, lacks the IDAES 2.0 features, most notably removing the `default={...}` kwarg for `ProcessBlock` (see the commit-by-commit comparison here: https://github.com/dguittet/idaes-pse/compare/2.0.0.a4...gmlc-dispatches:2.0.0.dev3.dispatches.22.10.06).

If we know that `DoubleLoopOptimization.ipynb` will need to be reworked anyway, we might just want to skip it entirely from CI until then so that this PR can be merged.

**Comment by radhakrishnatg** [comment]
@lbianchi-lbl @dguittet I was planning to remove the version check so that it can use the IDAES version that the entire repo is using. That's when I found that the `ThermalGeneratorModelData` class is missing. I feel that the easiest thing to do is to skip the notebook for now. And, remove all the version checks from the renewable case study notebooks in another PR later on. But if the changes are minor, I can make them in this PR.

**Comment by lbianchi-lbl** [comment]
@radhakrishnatg I've modified the CI workflow so that the steps where `DoubleLoopOptimization.ipynb` would be run are skipped instead. All checks are passing now, except for the Codecov one, which is to be expected since the USC discharge tests are not being run. I'll go ahead and merge - thanks for all your work on this!

**Pull request merged**
