### PR TITLE
Add steady state surrogates code

### PR DESCRIPTION
**Pull request by radhakrishnatg**
## Summary/Motivation:
This PR brings the steady state surrogate code from Jordan's fork to the DISPATCHES repo. The code requires some formatting, so the PR is not initiated directly from Jordan's fork. The documentation for the steady state surrogates in PR #107 will be updated based on the changes in this PR.

## Changes proposed in this PR:
- Created `util` folder for general utility functions. 
- Created a method to build surrogates using either ALAMO or Keras or Scikit for a given input-output data
- Added the simple rankine cycle code as another case study
- Added the code for steady state design with market surrogates

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by radhakrishnatg** [comment]
Questions:
- Should we save the Prescient runs data in the `dispatches` repo or in the `dispatches_sample_data` repo?
- Currently, the steady state design code is saved in the `workflow` folder. Is this the right place for this code?
- Should we also save the surrogate model files generated by ALAMO, Keras and Scikit?

**Comment by adowling2** [comment]
Discussion from today:
* Move the input data for surrogate training to `dispatches/sample-data`. Create an issue with a link to the data.
* Keep results from surrogate models in main dispatches repo.
* Nice to have TensorFlow or Keras support in CI. Okay to not include ALAMO in CI.

**Comment by adowling2** [comment]
We decided to merge #107 today and this PR should update the documentation with the appropriate changes.

**Comment by adowling2** [comment]
Now that #107 is merged, this current PR should also update the documentation to reflect any changes in the code.

**Comment by radhakrishnatg** [comment]
New costing API in IDAES makes the simple rankine cycle code incompatible with IDAES 2.0. Working on making updates to the Rankine cycle code.

**Comment by lbianchi-lbl** [comment]
- @radhakrishnatg: re-run the `surrogate_design_keras.ipynb` files, save, and commit again; this should fix the notebook static check that looks at the cell execution order
- @lbianchi-lbl: look at the changes files and determine what needs to be done to be able to access serialized Keras models where they're needed

**Comment by lbianchi-lbl** [comment]
@lbianchi-lbl will keep an eye on the notebook failures. It seems it could be due to one of the cells having a runtime that's very close to the timeout threshold.

**Comment by radhakrishnatg** [comment]
Hi @Xinhe-Chen Could you please review the PR and approve it?

**Review by Xinhe-Chen — APPROVED** [review]
I think this PR looks good to me. By the way, shall we consider setting up a repo for the surrogate model files just like we put the original training data into a separate repo.

**Comment by ksbeattie** [comment]
@adowling2, review please.

**Review by adowling2 — APPROVED** [review]
This is ready to merge once tests pass.

**Pull request merged**
