### PR TITLE
Fix concrete tube thermal storage / heat-exchanger docs

### PR DESCRIPTION
**Pull request by dangunter**
## Changes proposed in this PR:
- Any necessary tweaks to docstrings in code
- Modify RST in docs tree to show main class from module

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by andrewlee94 — APPROVED** [review]
Looks fine to me.

**Comment by dangunter** [comment]
@dguittet and attn: @ksbeattie , @lbianchi-lbl  - for some reason the test_battery.py module is failing in the tests (I didn't modify it or any of its dependencies afaik). Any ideas?

**Comment by lbianchi-lbl** [comment]
@dangunter The errors seem to point to Pyomo, possibly a change introduced with the latest release? I checked in the CI environment, and the installed Pyomo version is 6.1.1.

```txt
ERROR    pyomo.core:constraint.py:761 Rule failed when generating expression for Constraint fs.battery.state_evolution with index None:
IndexError: Constraint 'fs.battery.state_evolution': Cannot initialize multiple indices of a constraint with a single expression
ERROR    pyomo.core:block.py:1092 Constructing component 'fs.battery.state_evolution' from data=None failed:
IndexError: Constraint 'fs.battery.state_evolution': Cannot initialize multiple indices of a constraint with a single expression
ERROR    idaes.core.process_block:process_block.py:40 Failure in build: fs.battery
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/idaes/core/process_block.py", line 37, in _rule_default
    b.build()
  File "/home/runner/work/dispatches/dispatches/dispatches/models/renewables_case/battery.py", line 139, in build
    @self.Constraint(self.flowsheet().config.time)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/pyomo/core/base/block.py", line 69, in __call__
    self._component(*self._args, rule=rule, **(self._kwds))
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/pyomo/core/base/block.py", line 541, in __setattr__
    self.add_component(name, val)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/pyomo/core/base/block.py", line 1086, in add_component
    val.construct(data)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/pyomo/core/base/constraint.py", line 735, in construct
    (self.name,) )
IndexError: Constraint 'fs.battery.state_evolution': Cannot initialize multiple indices of a constraint with a single expression
ERROR    pyomo.core:block.py:1092 Constructing component 'fs.battery' from data=None failed:
IndexError: Constraint 'fs.battery.state_evolution': Cannot initialize multiple indices of a constraint with a single expression
```

**Comment by andrewlee94** [comment]
@lbianchi-lbl @dangunter Yes, this looks like a change in the recent release of Pyomo. Something has changed in how things are constructed.

**Comment by jsiirola** [comment]
This is a result of better error checking:
```python
        @self.Constraint(self.flowsheet().config.time)
        def state_evolution(b):
            return b.state_of_charge == b.initial_state_of_charge + (
                    b.charging_eta * b.dt * b.elec_in
                    - b.dt / b.discharging_eta * b.elec_out)
```
You are declaring a Constraint indexed by time, but the rule is *not* indexed by time (so you get the same expression for all points in time: ergo the exception about using the same expression to initialize multiple constraints)

**Comment by dguittet** [comment]
Unblocking this wtih #59

**Comment by dguittet** [comment]
Thanks! 

@dangunter Main is passing now, can you merge in the newest changes?

**Review by ksbeattie — APPROVED** [review]
LGTM

**Pull request merged**
