### PR TITLE
Update RAVEN and TEAL optional dependencies to May 2023 releases

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by joshua-cogliati-inl — APPROVED** [review]
This upgrades to the current RAVEN and TEAL, and I approve.

**Comment by lbianchi-lbl** [comment]
This seems to reduce, but not eliminate completely, the import-time warnings/outputs:

#### Before

```txt
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\matplotlib\__init__.py:169: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(module.__version__) < minver:
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\setuptools\_distutils\version.py:345: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
Matplotlib is building the font cache; this may take a moment.
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pkg_resources\__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
PluginFactory: No installed plugins detected.
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
<module 'TEAL.src.CashFlows' from 'C:\\hostedtoolcache\\windows\\Python\\3.8.10\\x64\\lib\\site-packages\\TEAL\\src\\CashFlows.py'>
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
<module 'TEAL.src.main' from 'C:\\hostedtoolcache\\windows\\Python\\3.8.10\\x64\\lib\\site-packages\\TEAL\\src\\main.py'>
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
{20: array([ 0.0375 ,  0.07219,  0.06677,  0.06177,  0.05713,  0.05285,
  declare_namespace(pkg)
        0.04888,  0.04522,  0.04462,  0.04461,  0.04462,  0.04461,
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.logging')`.
        0.04462,  0.04461,  0.04462,  0.04461,  0.04462,  0.04461,
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
        0.04462,  0.04461,  0.02231]), 15: array([ 0.05  ,  0.095 ,  0.0855,  0.077 ,  0.0693,  0.0623,  0.059 ,
  declare_namespace(pkg)
        0.059 ,  0.0591,  0.059 ,  0.0591,  0.059 ,  0.0591,  0.059 ,
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pkg_resources\__init__.py:2349: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
        0.0591,  0.0295]), 10: array([ 0.1   ,  0.18  ,  0.144 ,  0.1152,  0.0922,  0.0737,  0.0655,
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
        0.0655,  0.0656,  0.0655,  0.0328]), 7: array([ 0.1429,  0.2449,  0.1749,  0.1249,  0.0893,  0.0892,  0.0893,
  declare_namespace(parent)
        0.0446]), 5: array([ 0.2   ,  0.32  ,  0.192 ,  0.1152,  0.1152,  0.0576]), 3: array([ 0.3333,  0.4445,  0.1481,  0.0741])}
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\xarray\core\pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\setuptools\_distutils\version.py:345: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\xarray\core\npcompat.py:89: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(np.__version__) >= "1.20.0":
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\xarray\core\pdcompat.py:45: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(pd.__version__) < "0.25.0":
```

#### After

```txt
Matplotlib is building the font cache; this may take a moment.
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pkg_resources\__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
<module 'TEAL.src.CashFlows' from 'C:\\hostedtoolcache\\windows\\Python\\3.8.10\\x64\\lib\\site-packages\\TEAL\\src\\CashFlows.py'>
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
<module 'TEAL.src.main' from 'C:\\hostedtoolcache\\windows\\Python\\3.8.10\\x64\\lib\\site-packages\\TEAL\\src\\main.py'>
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
{20: array([ 0.0375 ,  0.07219,  0.06677,  0.06177,  0.05713,  0.05285,
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
        0.04888,  0.04522,  0.04462,  0.04461,  0.04462,  0.04461,
  declare_namespace(pkg)
        0.04462,  0.04461,  0.04462,  0.04461,  0.04462,  0.04461,
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.logging')`.
        0.04462,  0.04461,  0.02231]), 15: array([ 0.05  ,  0.095 ,  0.0855,  0.077 ,  0.0693,  0.0623,  0.059 ,
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
        0.059 ,  0.0591,  0.059 ,  0.0591,  0.059 ,  0.0591,  0.059 ,
  declare_namespace(pkg)
        0.0591,  0.0295]), 10: array([ 0.1   ,  0.18  ,  0.144 ,  0.1152,  0.0922,  0.0737,  0.0655,
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pkg_resources\__init__.py:2349: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
        0.0655,  0.0656,  0.0655,  0.0328]), 7: array([ 0.1429,  0.2449,  0.1749,  0.1249,  0.0893,  0.0892,  0.0893,
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
        0.0446]), 5: array([ 0.2   ,  0.32  ,  0.192 ,  0.1152,  0.1152,  0.0576]), 3: array([ 0.3333,  0.4445,  0.1481,  0.0741])}
  declare_namespace(parent)
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
```

In both cases, the command is:

```sh
python -c "
from TEAL.src import CashFlows; print(CashFlows)
from TEAL.src import main; print(main)
from TEAL.src.Amortization import MACRS; print(MACRS)
"
```

**Comment by joshua-cogliati-inl** [comment]
Hm, I wonder what is causing that.  If I just install TEAL on linux, I don't get those warnings.
```
python3.8 -m venv test
source test/bin/activate
python3.8 -m pip  install teal_ravenframework
Collecting teal_ravenframework
  Downloading teal_ravenframework-0.4-py3-none-any.whl (35 kB)
```
```
python3.8
Python 3.8.16 (default, Dec  7 2022, 00:00:00) 
[GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import TEAL
>>> from TEAL.src import CashFlows
>>> from TEAL.src import main
>>> from TEAL.src.Amortization import MACRS
>>> 
```

**Review by ksbeattie — APPROVED** [review]
LGTM

**Pull request merged**
