### PR TITLE
fe_design_w_market_surrogate_files

### PR DESCRIPTION
**Pull request by nareshsusarla**
## Summary/Motivation:
This PR adds files for FE case design using market surrogates

## Changes proposed in this PR:
- adds the multiperiod design flowsheet for FE case
- adds keras surrogate models
- adds json files for scaling factors, representative days, and capacity factors

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md and COPYRIGHT.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by ksbeattie** [comment]
This is waiting for PR #179

**Comment by lbianchi-lbl** [comment]
This might have to wait until ~1st week of June but is still planned to be in the June release.

**Comment by lbianchi-lbl** [comment]
@nareshsusarla any updates on this? It would have to be merged within the next few days for it to be in the June release.

**Comment by ksbeattie** [comment]
This will not be for the June/Final release.

**Comment by adowling2** [comment]
@nareshsusarla, please instead merge this into a non-main branch. Also include notes on next steps/why we pivoted from this

**Comment by nareshsusarla** [comment]
A different PR #216 is created to merge these files with a feature branch. So, this PR is now closed

**Pull request closed without merging**
